### ISSUE TITLE
Initialize database for People object

### ISSUE THREAD

**Issue by v-apa** [v-apa/TestSolution#2]
### Tasks

- [x] Create the  People table
- [x] Seed the People table
- [x] Create the GetAll procedure
- [x] #5
- [x] #3
- [x] #4
